// Generated by https://quicktype.io

export interface ICompany {
    name:        string;
    email:       string;
    description: string;
    location:    string;
    phone:       string;
    website:     string;
    token:       string;
    username:    string;
    image:       string;
    banner:      string;
}

