// Generated by https://quicktype.io

export interface ICompany {
    name:        string;
    email:       string;
    description: string;
    location:    string;
    phone:       string;
    website:     string;
    password:    string;
    username:    string;
    vacancies:   any[];
    image:       string;
    banner:      string;
}
