// Generated by https://quicktype.io

export interface IUser {
    _id:      string;
    username: string;
    email:    string;
    role:     string;
    name:     string;
    image:    string;
    token: string;
}

export interface User {
    _id:      string;
    username: string;
    email:    string;
    role:     string;
    name:     string;
    image:    string;
}
