// Generated by https://quicktype.io

export interface IUserProfile {
    email:    string;
    image:    string;
    lastname: string;
    name:     string;
    role:     string;
    username: string;
    profile:  Profile;
}

export interface Profile {
    banner:         string;
    birthday:       string;
    career:         string;
    certificates:   IUserProfileCertificates[];
    description:    string;
    experience:     IUserProfileExperience[];
    phone:          string;
    semester:       string;
    socialNetworks: IUserProfileSocialNetworks[];
    years:          null;
}

export interface IUserProfileCertificates {
    name        : string;
    dateOfIssue : string;
    company     : string;
    hours       : number;
}

export interface IUserProfileExperience {
    position    : string;
    company     : string;
    startDate   : string;
    endingtDate : string;
}

export interface IUserProfileSocialNetworks {
    name        : string;
    url         : string;
}